### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by Lars147** [lightningblade1/TaskManagement#1]
Hi there,

thank you for inviting me to the repo. 

I wanted to check if this repo is already finally submitted or are there some changes coming? I noticed that a some files would be missing for a complete Django project.

**Comment by lightningblade1** [comment]
i have uploaded the relevant files

**Comment by Lars147** [comment]
I can still see no files.

I saw that there is no a second branch called "master" next to the default branch "main" but it seems to be a different project.

**Comment by lightningblade1** [comment]
I apologize this was an old project that had a similar name and I committed it by mistake. I have made the relevant changes please let me know what you think

**Comment by Lars147** [comment]
Great! I can see the files now. I hope I can give you proper feedback until the end of the week :)
